name: Dependency Cascade Example (Custom Action)

on:
  push:
    branches: [ main ]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Query Affected Services
        id: affected
        uses: taco-xyz/dependency-cascade-query-simple-action@v0.1.0
        with:
          head-ref: ${{ github.sha }}
          before-sha: ${{ github.event.before }}

      # Example of using the output
      - name: Use the results
        run: |
          echo "Affected services: ${{ steps.affected.outputs.affected-services }}"
          echo "Changed files: ${{ steps.affected.outputs.changed-files }}"