name: Dependency Cascade Example

on:
  push:
    branches: [ main ]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Pull dependency-cascade image
        run: docker pull ghcr.io/tubarao312/dependency-cascade:main
        
      - name: Get changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "files=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          else
            echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          fi

      - name: Prepare dependency graph
        id: prepare
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/tubarao312/dependency-cascade:main prepare -d . > dependency-graph.json
          
      - name: Print dependency graph
        run: |
          cat dependency-graph.json

      - name: Query affected nodes 
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/tubarao312/dependency-cascade:main query -g dependency-graph.json -f $(echo '${{ steps.changed-files.outputs.files }}' | jq -r '.[]' | tr '\n' ' ')