name: Dependency Cascade Example

on:
  push:
    branches: [ main ]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Pull dependency-cascade image
        run: docker pull ghcr.io/tubarao312/dependency-cascade:main
        
      - name: Get changed files
        id: changed-files
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare dependency graph
        id: prepare
        run: |
          echo "graph=$(docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/tubarao312/dependency-cascade:main prepare -d .)" >> $GITHUB_OUTPUT

      - name: Query affected nodes 
        run: |
          graph_json='${{ steps.prepare.outputs.graph }}'
          readarray -t files <<< '${{ steps.changed-files.outputs.files }}'
          docker run --rm -i -v $(pwd):/workspace -w /workspace ghcr.io/tubarao312/dependency-cascade:main query -g "$graph_json" -f "${files[@]}"